# Generated by Django 5.0.3 on 2024-03-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'Cursos',
            },
        ),
    ]
