# Generated by Django 5.0.3 on 2024-03-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='creditos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cursos',
            name='precio',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
