# Generated by Django 5.0.3 on 2024-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0005_alter_cursos_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='fecha',
            new_name='fechaCreacion',
        ),
        migrations.AddField(
            model_name='cursos',
            name='fechaFin',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='fechaInicio',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
