# Generated by Django 5.0.3 on 2024-03-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0007_estudiantes_profesores_cursos_fkprofesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='creditos',
            new_name='clases',
        ),
    ]
