# Generated by Django 5.0.3 on 2024-03-14 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0008_rename_creditos_cursos_clases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='fkProfesor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.profesores', verbose_name='Profesor'),
        ),
    ]
