# Generated by Django 5.0.3 on 2024-03-16 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0009_alter_cursos_fkprofesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('idInscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fkCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.cursos')),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.estudiantes')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'Inscripciones',
            },
        ),
    ]
