# Generated by Django 5.0.3 on 2024-03-18 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0010_inscripciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('idAsistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('fkCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.cursos')),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.estudiantes')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'Asistencias',
            },
        ),
    ]
