# Generated by Django 5.0.3 on 2024-03-18 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0011_inscripciones_disponible_asistencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('idCalificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion1', models.PositiveIntegerField(verbose_name='Nota 1')),
                ('calificacion2', models.PositiveIntegerField(verbose_name='Nota 2')),
                ('calificacion3', models.PositiveIntegerField(verbose_name='Nota 3')),
                ('promedio', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fkCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.cursos')),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.estudiantes')),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'Calificaciones',
            },
        ),
    ]
