# Generated by Django 5.0.3 on 2024-03-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0012_calificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='calificacion1',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Nota 1'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='calificacion2',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Nota 2'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='calificacion3',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Nota 3'),
        ),
    ]
