# Generated by Django 5.0.3 on 2024-03-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0013_alter_calificaciones_calificacion1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='promedio',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
