# Generated by Django 5.0.3 on 2024-03-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0019_alter_calificaciones_calificacion1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='fkCurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='asistencias',
            name='fkEstudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.estudiantes', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='fkCurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='fkEstudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.estudiantes', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='fkCurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='fkEstudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.estudiantes', verbose_name='Estudiante'),
        ),
    ]
