# Generated by Django 5.0.3 on 2024-03-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0020_alter_asistencias_fkcurso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencias',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='asistencias',
            name='presente',
        ),
        migrations.AddField(
            model_name='asistencias',
            name='asistencia1',
            field=models.BooleanField(default=False, verbose_name='As #1'),
        ),
        migrations.AddField(
            model_name='asistencias',
            name='asistencia2',
            field=models.BooleanField(default=False, verbose_name='As #2'),
        ),
        migrations.AddField(
            model_name='asistencias',
            name='asistencia3',
            field=models.BooleanField(default=False, verbose_name='As #3'),
        ),
        migrations.AddField(
            model_name='asistencias',
            name='asistencia4',
            field=models.BooleanField(default=False, verbose_name='As #4'),
        ),
    ]
