# Generated by Django 5.0.3 on 2024-03-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0021_remove_asistencias_fecha_remove_asistencias_presente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='asistencia1',
            field=models.BooleanField(default=False, verbose_name='A=> #1'),
        ),
        migrations.AlterField(
            model_name='asistencias',
            name='asistencia2',
            field=models.BooleanField(default=False, verbose_name='A=> #2'),
        ),
        migrations.AlterField(
            model_name='asistencias',
            name='asistencia3',
            field=models.BooleanField(default=False, verbose_name='A=> #3'),
        ),
        migrations.AlterField(
            model_name='asistencias',
            name='asistencia4',
            field=models.BooleanField(default=False, verbose_name='A=> #4'),
        ),
    ]
