# Generated by Django 5.0.3 on 2024-03-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0025_asistencias_fkprofesor_calificaciones_fkprofesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='fkProfesor',
        ),
    ]
