# Generated by Django 5.0.3 on 2024-03-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0026_remove_calificaciones_fkprofesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='fkProfesor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.profesores', verbose_name='Profesor'),
        ),
    ]
