# Generated by Django 5.0.3 on 2024-03-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0028_asistencias_porcentajeasistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='porcentajeAsistencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='% Asistencia'),
        ),
    ]
