# Generated by Django 5.0.3 on 2024-03-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0031_remove_estudiantes_fkusuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor')], default='estudiante', max_length=20),
        ),
        migrations.AddField(
            model_name='profesores',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor')], default='profesor', max_length=20),
        ),
    ]
