# Generated by Django 5.0.3 on 2024-03-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0032_estudiantes_rol_profesores_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='rol',
        ),
    ]
