# Generated by Django 5.0.3 on 2024-03-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0035_alter_estudiantes_ciudad_alter_profesores_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='ciudad',
            field=models.CharField(default='Medellin', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='ciudad',
            field=models.CharField(default='Medellin', max_length=100, null=True),
        ),
    ]
