# Generated by Django 5.0.3 on 2024-03-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0036_alter_estudiantes_ciudad_alter_profesores_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='ciudad',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='ciudad',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
