# Generated by Django 5.0.3 on 2024-03-27 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0037_alter_estudiantes_ciudad_alter_profesores_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fkProfesor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myAppGestionAcademia.profesores', verbose_name='Profesor'),
        ),
    ]
