# Generated by Django 5.0.3 on 2024-04-02 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestionAcademia', '0038_cursos_version_alter_cursos_fkprofesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='fkCurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='asistencias',
            name='fkEstudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.estudiantes', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='asistencias',
            name='fkProfesor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.profesores', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='fkCurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='fkEstudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.estudiantes', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='fkProfesor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myAppGestionAcademia.profesores', verbose_name='Profesor'),
        ),
    ]
